export const defaultState = {
  rating: 7.4,
  netWorth: { current: 50000, yearTargets: [70000, 100000, 150000, 200000, 250000] },
  career: {
    target: "AE role — €70k+ base, €100-120k OTE",
    stage: "Undeniable at Qstream, AE interviews",
    pct: 45,
    notes: "",
  },
  incomeSources: [
    { name: "Corporate salary", active: true },
    { name: "Content monetisation", active: false },
    { name: "House of Astar membership", active: false },
    { name: "Fractional consulting", active: false },
    { name: "Investment and equity returns", active: false },
  ],
  deals: [
    { name: "House of Astar", stage: "Planning", next: "" },
    { name: "Crux", stage: "Concept", next: "" },
    { name: "Know Your Lifestyle", stage: "Live", next: "" },
    { name: "Gaitheria", stage: "Concept", next: "" },
    { name: "Nigeria plays", stage: "Concept", next: "" },
    { name: "Casa Del Imade", stage: "Concept", next: "" },
  ],
  body: { weight: "", bf: "", log: [] as string[] },
  combat: [
    { text: "Boxing", done: false },
    { text: "Wrestling", done: false },
    { text: "BJJ", done: false },
  ],
  weekOffset: 0,
  dailyHabits: [
    "Pray", "Bible", "Journal", "Languages — Edo and Spanish", "Articulation practice",
    "No phone first 30 mins", "Push ups", "Fasting", "Track calories on eating days",
    "Leave house put together", "Fragrance", "AE job search action", "Sales skill block",
    "Net worth check", "HTS action", "Substack", "YouTube", "Book / brainstorm",
    "Crux / Astar action", "Three priorities written", "7+ hours sleep", "Up before 7am",
  ].map((t, i) => ({ id: "d" + i, text: t })),
  dailyLog: [] as { habitId: string; date: string }[],
  weeklyHabits: [
    { id: "w0", text: "Gym", goal: 3 },
    { id: "w1", text: "Run", goal: 2 },
    { id: "w2", text: "Stretch", goal: 2 },
    { id: "w3", text: "Shave", goal: 3 },
  ],
  weeklyLog: [] as { habitId: string; date: string }[],
  monthDate: new Date().toISOString().slice(0, 7),
  monthly: [
    "Full net worth update", "Body composition check", "Career audit",
    "Crux and Astar review", "Content review", "One experience", "Read three year vision",
  ].map((t) => ({ text: t, done: false })),
  quarterGoals: [
    { category: "Career", text: "", completed: false },
    { category: "Ventures", text: "", completed: false },
    { category: "Body", text: "", completed: false },
    { category: "Finance", text: "", completed: false },
  ],
  bucketList: [
    { text: "Nigeria", category: "Travel", completed: false },
    { text: "NYC", category: "Travel", completed: false },
    { text: "Ibiza", category: "Travel", completed: false },
    { text: "Monaco", category: "Travel", completed: false },
    { text: "San Francisco", category: "Travel", completed: false },
    { text: "Miami", category: "Travel", completed: false },
    { text: "Marbella", category: "Travel", completed: false },
    { text: "French Riviera", category: "Travel", completed: false },
    { text: "Wimbledon", category: "Experience", completed: false },
    { text: "F1 race", category: "Experience", completed: false },
    { text: "French Open", category: "Experience", completed: false },
    { text: "A fashion week", category: "Experience", completed: false },
  ],
  yearReflections: { vision: "", nonNeg: "", focus: "", change: "" },
  weeklyFocus: "",
  weeklyWins: [] as string[],
  monthlyReflections: {} as Record<string, { right: string; change: string }>,
  milestones: [
    { text: "First Rolex", date: "On AE role + €70k net worth" },
    { text: "Manchester move", date: "" },
    { text: "Engaged", date: "Within 5 years" },
    { text: "Mercedes GLE Coupé", date: "" },
  ],
  fiveYearPlan: [
    { year: "Year 1 (27)", text: "Undeniable at Qstream, AE interviews begin Q4, €70k net worth, start combat sport, content brand launched, Astar founding conversations." },
    { year: "Year 2 (28)", text: "AE role landed, €100k net worth, Manchester move, content monetising, Astar Dublin and Manchester operational, 50-100 founding members." },
    { year: "Year 3 (29)", text: "Senior AE or team lead, €150k net worth, GLE purchased, 200+ Astar members, London chapter beginning, content real traction." },
    { year: "Year 4 (30)", text: "Sales Manager or Senior AE, €200k net worth, fractional consulting beginning, engaged, F1/fashion weeks/Wimbledon regular, 300+ Astar members." },
    { year: "Year 5 (31)", text: "Fractional CRO portfolio beginning, €250-300k net worth, €200-220k income, all five income sources operational, dream lifestyle substantially achieved, 500 Astar members." },
  ],
};

export type DashboardData = typeof defaultState;
